// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbVvV2ZIVaufMOuyiCLdgo8m6vH4s_qGo',
    appId: '1:812403812057:web:bc894a5d385df5cdcfc0c8',
    messagingSenderId: '812403812057',
    projectId: 'realview-2c08b',
    authDomain: 'realview-2c08b.firebaseapp.com',
    storageBucket: 'realview-2c08b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI-tRuPphf-dPWkK92mDRFPIx8R1ByGzA',
    appId: '1:812403812057:android:4cb621fd29a024a4cfc0c8',
    messagingSenderId: '812403812057',
    projectId: 'realview-2c08b',
    storageBucket: 'realview-2c08b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIzmX7sYmPXzWfGs5HScCorXeHf9LnrOM',
    appId: '1:812403812057:ios:bfdd554468cca62bcfc0c8',
    messagingSenderId: '812403812057',
    projectId: 'realview-2c08b',
    storageBucket: 'realview-2c08b.appspot.com',
    iosClientId: '812403812057-crfiqiujhltg7ovt3pgq6oh3f2v9b449.apps.googleusercontent.com',
    iosBundleId: 'com.example.unsplash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIzmX7sYmPXzWfGs5HScCorXeHf9LnrOM',
    appId: '1:812403812057:ios:9db5606b61ffe36bcfc0c8',
    messagingSenderId: '812403812057',
    projectId: 'realview-2c08b',
    storageBucket: 'realview-2c08b.appspot.com',
    iosClientId: '812403812057-36qjuvc6q4sptjpq80jvkeigl17j30n7.apps.googleusercontent.com',
    iosBundleId: 'com.example.unsplash.RunnerTests',
  );
}
